package com.philippmeyer.factory.entity;

import jakarta.persistence.*;

import java.util.Date;

/**
 * Represents a machine fault or disruption event (Stoerung) in the factory context.
 * This entity tracks the fault characteristics, timing, and recovery efforts.
 */
@Entity // Marks this class as a JPA entity, mapped to a database table.
public class Stoerung {

    @Id // Designates this field as the primary key.
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies the PK value is generated by the database (auto-increment).
    private int id; // Unique identifier for the disruption event.

    private String merkmal; // Characteristic or type of the fault (e.g., "Overheating", "Sensor Failure").

    @Temporal(TemporalType.TIMESTAMP) // Specifies that the Date field should be persisted as a full timestamp (date and time).
    private Date datum; // The date and time when the disruption occurred.

    private int anzahl_verbesserungen; // The count of improvements/fixes applied to resolve the fault.

    private int stoerminuten; // The duration of the disruption in minutes (downtime).

    /**
     * Default constructor required by JPA.
     */
    public Stoerung() {
        // Default constructor
    }

    /**
     * Provides a string representation of the object for logging and debugging.
     */
    @Override
    public String toString() {
        // Adjusted package name in toString() for cleaner output/consistency.
        return "com.philippmeyer.factory.entity.Stoerung{" +
                "id=" + id +
                ", merkmal='" + merkmal + '\'' +
                ", datum=" + datum +
                ", anzahl_verbesserungen=" + anzahl_verbesserungen +
                ", stoerminuten=" + stoerminuten +
                '}';
    }

    // --- Getters and Setters ---

    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public String getMerkmal() { return merkmal; }
    public void setMerkmal(String merkmal) { this.merkmal = merkmal; }

    public Date getDatum() { return datum; }
    public void setDatum(Date datum) { this.datum = datum; }

    public int getAnzahl_verbesserungen() { return anzahl_verbesserungen; }
    public void setAnzahl_verbesserungen(int anzahl_verbesserungen) { this.anzahl_verbesserungen = anzahl_verbesserungen; }

    public int getStoerminuten() { return stoerminuten; }
    public void setStoerminuten(int stoerminuten) { this.stoerminuten = stoerminuten; }
}